services:
  - type: web
    name: sistema-esquadrias
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 5000
